### ISSUE TITLE
Causes Phenom 100 Gears to Malfunction.

### ISSUE THREAD

**Issue by ERAUAir1533** [Qantas94Heavy/nose-wheel-steering#3]
The left main gear of the Phenom 100 spasms out of control when on the ground, causing the right gear to be out of control. It has been identified to be this extension.

**Comment by Qantas94Heavy** [comment]
This is a bug caused by a change in aircraft IDs by Xavier. `'5'` used to be the aircraft ID for the DC-3, but it's now used for the Phenom 100 instead.

I'll release an update to reflect the change in IDs shortly.
