### ISSUE TITLE
Extension causes 737 MAX 8 gear to stay down

### ISSUE THREAD

**Issue by ERAUAir1533** [Qantas94Heavy/nose-wheel-steering#4]
This extension causes the 737 MAX 8 by FLDG's right gear to stay down when you put the gear up. Also, when on the ground and you attempt to use the extension on the MAX 8, instead of turning the front gear, it bends the right main gear.

**Comment by Qantas94Heavy** [comment]
Hi, I believe the issue is with the configuration of the aircraft instead of the extension itself.

I've opened an internal FLDG tracking report for the issue to be fixed. Thanks for reporting!
