### ISSUE TITLE
Wrong ID for Certain Aircraft

### ISSUE THREAD

**Issue by ERAUAir1533** [Qantas94Heavy/nose-wheel-steering#5]
The nose wheel steering extension is causing the de Havilland DHC-6 Twin Otter's gears to spaz out, just as with the Phenom. This is because Xavier changed the IDs around for the planes again with the release of the Twotter.

**Comment by Qantas94Heavy** [comment]
Thanks for reporting this issue! This should be fixed in the latest release, v1.0.2.
